"""add owner relationship to notes

Revision ID: 2615bb3f4764
Revises: dde74b5a27d9
Create Date: 2026-07-27 17:04:20.987138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2615bb3f4764'
down_revision: Union[str, Sequence[str], None] = 'dde74b5a27d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
    "fk_notes_owner_id_users",
    "notes",
    "users",
    ["owner_id"],
    ["id"],
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    "fk_notes_owner_id_users",
    "notes",
    type_="foreignkey",
)
    op.drop_column('notes', 'owner_id')
    # ### end Alembic commands ###
